version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: focus-opal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: focus_opal_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: focus-opal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Prisma Studio (opcional - descomentar si quieres)
  # prisma-studio:
  #   image: node:20-alpine
  #   container_name: focus-opal-prisma-studio
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "5555:5555"
  #   command: npx prisma studio
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/focus_opal_ai

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: focus-opal-network

